clc;

StressRelaxationFunction =  fittype('a0+a1*exp(-x/tau1)+a2*exp(-x/tau2)',...
    'coefficients',{'a0','a1','a2','tau1','tau2'},...
    'dependent','y',...
    'independent','x');
Exp2Fit = fit(x_time_data',y_time_data','Exp2')            
StressRelaxationFit = fit(x_time_data',y_time_data', StressRelaxationFunction,...
    'StartPoint',[0 Exp2Fit.a Exp2Fit.c Exp2Fit.b Exp2Fit.d],...
    'MaxIter',1000,...
    'Robust','LAR');

plot(StressRelaxationFit,x_time_data,y_time_data);